services:
  svr_n8n:
    image: n8nio/n8n:1.71.3
    container_name: cont_n8n
    environment:
      - N8N_SECURE_COOKIE=false
      - GENERIC_TIMEZONE=Asia/Ho_Chi_Minh
      - N8N_EDITOR_BASE_URL=https://auto.dichvuchukyso.com
      - N8N_HOST=auto.dichvuchukyso.com
      - N8N_PORT=5678
    ports:
      - "80:5678"
    volumes:
      - /root/vol_n8n:/home/node/.n8n
